apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-id-backups
  namespace: pg-id

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 1Gi
