apiVersion: batch/v1
kind: CronJob

metadata:
  name: pg-id-backup
  namespace: pg-id

spec:
  schedule: "0 1 * * *"

  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          containers:
          - name: backup
            image: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie

            env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pg-id-app
                  key: username

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-id-app
                  key: password

            command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              pg_dump \
                -h pg-id-rw \
                -U "$PGUSER" \
                "$PGUSER" \
                | gzip > /backup/pg-id.sql.gz

            volumeMounts:
            - name: backup
              mountPath: /backup

          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: pg-id-backups
