apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: pg-id
  namespace: pg-id

spec:
  instances: 1
  monitoring:
    enablePodMonitor: true

  storage:
    storageClass: local-path
    size: 5Gi