apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-happyminds-ingress
  namespace: happyminds
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      limit_req zone=wp burst=5 nodelay;

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.happyminds.nl
        - happyminds.nl
      secretName: wordpress-happyminds-tls
  rules:
    - host: www.happyminds.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-happyminds
                port:
                  number: 80
    - host: happyminds.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-happyminds
                port:
                  number: 80
