apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-happyminds-ingress
  namespace: happyminds
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

nginx.ingress.kubernetes.io/configuration-snippet: |
  if ($request_uri = "/xmlrpc.php") {
    return 444;
  }

  if ($request_uri ~* "/wp-login.php") {
    limit_req zone=wp burst=5 nodelay;
  }

  if ($request_uri ~* "/wp-admin/") {
    limit_req zone=wp burst=10 nodelay;
  }
  
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.happyminds.nl
        - happyminds.nl
      secretName: wordpress-happyminds-tls
  rules:
    - host: www.happyminds.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-happyminds
                port:
                  number: 80
    - host: happyminds.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-happyminds
                port:
                  number: 80
``