grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorSelector: {}
    serviceMonitorSelector: {}