apiVersion: v1
kind: Service
metadata:
  name: mysite-service
  labels:
    app: mysite
spec:
  selector:
    app: mysite
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP            
