apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mysite-prjv-nl
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mysite.prjv.nl`)
      kind: Rule
      services:
        - name: mysite-external
          kind: TraefikService
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: mysite-external
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - url: "http://192.168.5.230"
