resources:
  #- namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - traefik-acme-pvc.yaml
  - ingressroute-argocd.yaml
  - ingressroute-mysite-prjv-nl.yaml
  - ingressroute-happyminds-nl.yaml
