apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    mprjv65/service: argocd
    mprjv65/type: platform
    mprjv65/role: controller
    mprjv65/depends_on: cert-manager:shared,nginx-ingress:shared
  annotations:
    mprjv65/owner: team-platform
spec:
  project: default
  source:
    repoURL: git@github.com:peter-kaagman/cluster.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
