apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Standaard instellingen voor ArgoCD
  url: https://argocd.prjv.nl
  admin.enabled: "true"
  # Voeg hier je repositories toe indien nodig
  repositories: |
    - url: https://github.com/peter-kaagman/cluster
  # Voeg hier je custom health checks toe indien gewenst
  resource.customizations.health.networking.k8s.io_Ingress: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Ingress exists"
    return hs
