apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  middlewares:
    - name: forwarded-headers
      namespace: argocd
  routes:
    - match: Host(`argocd.prjv.nl`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
          scheme: http
  tls:
    certResolver: letsencrypt
