# Kustomization voor ArgoCD App-of-Apps patroon
resources:
  - application-argocd.yaml
  - ingress-argocd-nginx.yaml
  - application-mysql.yaml
  - application-cert-manager.yaml
  - application-nginx-ingress.yaml
  - application-mysite.yaml
