# Kustomization voor ArgoCD App-of-Apps patroon
resources:
  - application-argocd.yaml
  - ingress-argocd.yaml
  - application-mysql.yaml
  - application-traefik.yaml
  - application-cert-manager.yaml
