# Kustomization voor ArgoCD App-of-Apps patroon
resources:
  - application-argocd.yaml
  - ingress-argocd-nginx.yaml
  - apps/application-mysql.yaml
  - apps/application-cert-manager.yaml
  - apps/application-nginx-ingress.yaml
  - apps/application-mysite.yaml
  - apps/application-happyminds.yaml
