server:
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - argocd.prjv.nl
    annotations: {}
    tls: []
configs:
  params:
    server.insecure: true
  cm:
    admin.enabled: true
    # oidc.config: |-
    #   # OIDC config voor SSO
