apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-driver
  namespace: argocd
  labels:
    mprjv65/service: nfs-csi-driver
    mprjv65/type: infrastructure
    mprjv65/role: storage
  annotations:
    mprjv65/owner: team-platform
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    chart: csi-driver-nfs
    targetRevision: v4.6.0
    helm:
      releaseName: nfs-csi-driver
      values: |
        controller:
          runOnControlPlane: false
          nodeSelector: {}
          tolerations: []
        node:
          runOnControlPlane: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
