apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    mprjv65/service: grafana
    mprjv65/type: observability
    mprjv65/role: visualization
  annotations:
    mprjv65/owner: team-platform
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.15
      helm:
        releaseName: grafana
        valueFiles:
          - $values/grafana/values.yaml
    - repoURL: https://github.com/peter-kaagman/cluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/peter-kaagman/cluster.git
      targetRevision: main
      path: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
