apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/peter-kaagman/cluster.git
    path: mysql
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true