apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inspiration
  namespace: argocd
  labels:
    mprjv65/service: inspiration
    mprjv65/type: service
    mprjv65/role: frontend
  annotations:
    mprjv65/depends_on: mysql
    mprjv65/owner: team-web
spec:
  project: default
  source:
    repoURL: 'https://github.com/peter-kaagman/cluster.git'
    targetRevision: main
    path: inspiration
  destination:
    server: https://kubernetes.default.svc
    namespace: inspiration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true