apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  labels:
    mprjv65/service: fluent-bit
    mprjv65/type: observability
    mprjv65/role: logging
  annotations:
    mprjv65/owner: team-platform

spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.57.7

      helm:
        releaseName: fluent-bit
        valueFiles:
          - $values/fluent-bit/values.yaml
    - repoURL: https://github.com/peter-kaagman/cluster.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true