apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  labels:
    mprjv65/service: fluent-bit
    mprjv65/type: observability
    mprjv65/role: logging
  annotations:
    mprjv65/owner: team-platform

spec:
  project: default

  source:
    repoURL: 'https://github.com/peter-kaagman/cluster.git'
    targetRevision: main
    path: fluent-bit

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true