apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: mysql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-secret
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: secret/mysql
        property: MYSQL_ROOT_PASSWORD
    - secretKey: mysql-root-password
      remoteRef:
        key: secret/mysql
        property: MYSQL_ROOT_PASSWORD
    - secretKey: mysql-password
      remoteRef:
        key: secret/mysql
        property: MYSQL_ROOT_PASSWORD
