apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-bitnami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: 9.22.0
    helm:
      values: |
        auth:
          existingSecret: mysql-secret
          existingSecretPasswordKey: MYSQL_ROOT_PASSWORD
        image:
          tag: 8.0
        primary:
          persistence:
            enabled: true
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
