apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/external-secrets/external-secrets
    targetRevision: v0.9.3 # kies de juiste versie voor jouw setup
    path: deploy/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: {}
