apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/repository-secret-name: dockerhub-creds
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: mysql
    targetRevision: 14.1.2
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated: {}
