apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io
    chart: bitnamicharts/mysql
    targetRevision: 14.0.3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated: {}